steps:
    -
        name: node:alpine
        entrypoint: npm
        args:
          - install
        dir: '/workspace/pwadb'

    -
        name: node:alpine
        entrypoint: npm
        args:
            - run
            - build
            - "--"
            - pwadb-lib
            - "--prod"
        dir: '/workspace/pwadb'

    -   
        name: node:alpine
        entrypoint: /bin/sh
        args:
        - '-c'
        - |
            npm config set @impriyanshub:registry ${_GIT_REGISTRY} &&
            npm config set //npm.pkg.github.com/:_authToken ${_NPM_TOKEN} &&
            npm publish
        dir: '/workspace/pwadb/dist/pwadb-lib'