steps:
  -
    id: Build
    name: node:16
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
          yarn && yarn nx build pwadb-lib --skip-nx-cache
    dir: '/workspace/pwadb-nx'
  -   
    id: Publish
    name: node:16
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
        npm config set @advance-tools:registry=https://npm.pkg.github.com &&
        npm config set //npm.pkg.github.com/:_authToken=${_NPM_TOKEN} &&
        npm publish
    dir: '/workspace/pwadb-nx/dist/libs/pwadb-lib'